### PR TITLE
Refactor and Resolve Issues of the Token Page

### PR DESCRIPTION
**Pull request by AlirezaRa94**
To address #47

### CODE REVIEW

**Comment by shankari** [comment]
any updates on this?

**Comment by AlirezaRa94** [comment]
I am going to add some more commits this week.

**Comment by shankari** [comment]
@AlirezaRa94 is this ever going to move out of draft mode?

**Comment by AlirezaRa94** [comment]
@shankari I collaborated with another team at UNSW for the past two months and didn't have the opportunity to address these. I've recently returned, and I'm committed to completing these PRs.

**Pull request closed without merging**
