### PR TITLE
Feat/user page

### PR DESCRIPTION
**Pull request by AlirezaRa94**
This page offers the following functionalities:

User Selection: Users can select a user token (presumably representing a specific user) from a dropdown.

Statistics Cards: The page displays statistics cards, showing various user-related metrics such as user-specific data.

Trips by Date Table: A table presents trip data grouped by date, showcasing total trips and labelled trips.

Trips Heatmap: An interactive map presents trip locations using a heatmap visualization.

Date Dropdown: Users can select a date to display detailed trips or places data for that day.

Trips and Places Tabs: Users can switch between "Trips" and "Places" tabs to explore different aspects of data.

Trips and Places Tables: Depending on the selected tab, tables display detailed information about trips or places data for the selected date.

Overall, the user details page provides an interactive interface to explore user-specific data, focusing on trips, places, and associated statistics. Users can select a user, view key metrics, visualize trip locations, and delve into detailed trips or place data.

### CODE REVIEW

**Comment by shankari** [comment]
@AlirezaRa94 I don't see any dynamic config of this feature. At the minimum, we want to be able to control the display of spatio-temporal information. There are some partners who do not want to see any user-specific location data.

**Comment by AlirezaRa94** [comment]
> @AlirezaRa94 I don't see any dynamic config of this feature. At the minimum, we want to be able to control the display of spatio-temporal information. There are some partners who do not want to see any user-specific location data.

This is not yet completed and does not support dynamic config. I will fix them.

**Comment by shankari** [comment]
screenshots would be helpful as well

**Comment by shankari** [comment]
@AlirezaRa94 is this ever going to move out of draft mode?

**Pull request closed without merging**
