### PR TITLE
Reverted #124 and Added Logging

### PR DESCRIPTION
**Pull request by TeachMeTW**
# Revert Batching Changes and Implement Baseline Logging

### Changes Implemented
- **Reverted to Baseline**
  - Rolled back previous batching changes to establish a stable performance baseline.
  
- **Implemented Baseline Logging**
  - Logging to `add_user_stats` and `render_content`

## Testing Performed
- **Reversion Verification**
  - Confirmed that all batching changes have been successfully reverted.
  - Ensured no new issues or regressions were introduced by the reversion* (TBD).

## Related Issues
- Part of [#141](https://github.com/your-repo/issues/141) - Temporary Logging
- Part of [Project Plan](https://github.com/e-mission/op-admin-dashboard/issues/145) - Baseline Setup #145 

## Notes
- This PR establishes the baseline necessary for assessing the impact of future batching and performance improvements.

### CODE REVIEW

**Comment by TeachMeTW** [comment]
@shankari @JGreenlee please review

**Review by shankari — APPROVED** [review]
Since this change is going to be reverted anyway, I don't care as much about its code quality, just as long as it works.

@TeachMeTW can you please indicate how you tested this? I am deploying it to staging regardless.

**Comment by TeachMeTW** [comment]
> Since this change is going to be reverted anyway, I don't care as much about its code quality, just as long as it works.
> 
> 
> 
> @TeachMeTW can you please indicate how you tested this? I am deploying it to staging regardless.

It was a simple test, just loaded up a dataset and watched the UUIDs tab load like previously. I tested with open access and load times came to be about 280 seconds.

**Comment by TeachMeTW** [comment]
@shankari I missed that; Trips and every tab should work know. See #147

**Comment by shankari** [comment]
I hope this is a learning experience on the importance of testing _everything_ while making changes.
OpenPATH is complex, and even the admin dashboard is complex.
Changes can cause regressions, and it is important to verify that all existing functionality works.

After we have verified this on staging, we need to revisit the proposed timeline in https://github.com/e-mission/op-admin-dashboard/issues/145

**Pull request merged**
